<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedidos [
        <!ELEMENT pedidos (pedido)*>
        <!ELEMENT pedido (destinatario|articulo|fechaEntrega)*>
        <!ELEMENT destinatario (nombre|apellido|domicilio)*>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT apellido (#PCDATA)>
        <!ELEMENT domicilio (#PCDATA)>
        <!ELEMENT articulo (vehiculo|modelo|cantidad)*>
        <!ELEMENT vehiculo (#PCDATA)>
        <!ATTLIST vehiculo
                tipo CDATA #REQUIRED>
        <!ELEMENT modelo (#PCDATA)>
        <!ELEMENT cantidad (#PCDATA)>
        <!ELEMENT fechaEntrega (#PCDATA)>
        ]>
<pedidos>
    <pedido>
        <destinatario>
            <nombre>Juan</nombre>
            <apellido>Delgado Mart√≠nez</apellido>
            <domicilio>calle Barco 4, tercer piso, letra A</domicilio>
        </destinatario>
        <articulo>
            <vehiculo tipo="bicicleta">bicicleta</vehiculo>
            <modelo>A2023</modelo>
            <cantidad>1</cantidad>
        </articulo>
        <fechaEntrega>19-5-2000</fechaEntrega>
    </pedido>
</pedidos>