<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Biblioteca [
        <!ELEMENT Biblioteca (FichadePrestamo|FechaSalida|Entrega|FirmaRecibido)*>
        <!ELEMENT FichadePrestamo (DatosLector|DatosLibro)*>
        <!ELEMENT DatosLector (Nombre|Apellido|Domicilio|Telefono)*>
        <!ELEMENT Nombre (#PCDATA)>
        <!ELEMENT Apellido (#PCDATA)>
        <!ELEMENT Domicilio (#PCDATA)>
        <!ELEMENT Telefono (#PCDATA)>
        <!ELEMENT DatosLibro (Autor|Titulo|Clasificacion)*>
        <!ELEMENT Autor (#PCDATA)>
        <!ELEMENT Titulo (#PCDATA)>
        <!ELEMENT Clasificacion (#PCDATA)>
        <!ELEMENT FechaSalida (#PCDATA)>
        <!ELEMENT Entrega (#PCDATA)>
        <!ELEMENT FirmaRecibido (#PCDATA)>
        ]>
<Biblioteca>
    <FichadePrestamo>
        <DatosLector>
                <Nombre></Nombre>
                <Apellido></Apellido>
                <Domicilio></Domicilio>
                <Telefono></Telefono>
        </DatosLector>
        <DatosLibro>
            <Autor></Autor>
            <Titulo></Titulo>
            <Clasificacion></Clasificacion>
        </DatosLibro>
    </FichadePrestamo>
    <FechaSalida>
    </FechaSalida>
    <Entrega>
    </Entrega>
    <FirmaRecibido>
    </FirmaRecibido>
</Biblioteca>
