<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE diccionarios [
        <!ELEMENT diccionarios (idiomas|palabras|autor)*>
        <!ELEMENT idiomas (idioma)*>
        <!ELEMENT idioma (#PCDATA)>
        <!ATTLIST idioma
                id CDATA #REQUIRED>
        <!ELEMENT palabras (palabra)*>
        <!ELEMENT palabra (#PCDATA)>
        <!ATTLIST palabra
                id CDATA #REQUIRED>
        <!ELEMENT autor (#PCDATA)>
        ]>
<diccionarios>
    <idiomas>
        <idioma id="es">español</idioma>
        <idioma id="fr">francés</idioma>
        <idioma id="en">inglés</idioma>
    </idiomas>
    <palabras>
        <palabra id="es"> perro </palabra>
        <palabra id="en"> perro </palabra>
        <palabra id="fr"> perro </palabra>
    </palabras>
        <autor>Acme &amp; Co.</autor>
</diccionarios>