<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE documentos [
        <!ELEMENT documentos (documento)*>
        <!ELEMENT documento (contenido)*>
        <!ELEMENT contenido (autor|fecha|punto)*>
        <!ELEMENT autor (#PCDATA)>
        <!ELEMENT fecha (#PCDATA)>
        <!ATTLIST fecha
                id CDATA #REQUIRED>
        <!ELEMENT punto (#PCDATA)>
        <!ATTLIST punto
                id CDATA #REQUIRED>
        ]>
<documentos>
    <documento>
        <contenido>
            <autor />Bartolom√© Sintes Marco
            <fecha id="30/05/11"></fecha>
            <punto id ="1"> XML significa eXtensible Markup Languages</punto>
        </contenido>
    </documento>
</documentos>